### ISSUE TITLE
Activity Diagram

### ISSUE THREAD

**Issue by smarbal** [Seb1903/bovelo_manager#1]
This is the activity diagram :  

https://lucid.app/documents/view/9a903477-747d-4a87-b3f7-fb47c50f605c

**Comment by Seb1903** [comment]
https://lucid.app/publicSegments/view/840031b6-e42e-4786-a797-0eb8fe24b44f/image.png

**Comment by Seb1903** [comment]
This is the activity diagram :  
https://lucidchart.com/documents/view/9a903477-747d-4a87-b3f7-fb47c50f605c
