### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by troy-dem** [Seb1903/bovelo_manager#5]
#AB52 add sequence diagram for the catalog: https://lucid.app/documents/view/570fe02b-57dd-400f-bd7d-0c7af648c352

**Comment by ghost** [comment]
https://lucid.app/documents/view/8ddc552c-f604-4018-88b7-53487ddf7540

**Comment by NMI97** [comment]
# Sequence Diagrams
##  Supplier Order
- Order part from supplier
## Bike Production
- Bikes production process
- Broken parts report 
## Bike Model/Part
- Adding new bike part
- Adding new bike model

**Comment by troy-dem** [comment]
[AB#755](https://dev.azure.com/ECAM3BE/971c7354-0baf-4798-9e91-c470fcd1ded4/_workitems/edit/755) Sequence diagram of a supplier order

[https://lucid.app/lucidchart/cec42233-dc50-458f-ae1c-218914939d81/view?page=0_0#](url)
