### ISSUE TITLE
Partstock Search

### ISSUE THREAD

**Issue by NMI97** [Seb1903/bovelo_manager#58]
In `ManagerView/Partstock` View, there is bug when searching a part. 

![enter image description here](https://i.ibb.co/JRy4YB6/Partstock-bug.png)

**Comment by troy-dem** [comment]
Proposition of bug fix

![bug_fix](https://user-images.githubusercontent.com/60985336/121516461-85da2e80-c9ee-11eb-83d4-e37c4cbc2d80.png)

The name of the table was "part_stock_view" in code so it didn't fit the name in MySQL workbench "part**s**_stock_view".

Everything seems to work as expected after that fix.

I'll push the fix on main branch when it gets approved (positive reactions on post)

**Comment by NMI97** [comment]
Ok perfect, do a pull request when you are finished and close the issue after merge.

**Comment by troy-dem** [comment]
Closing the issue after merging pull request containing the bug fix
