### ISSUE TITLE
Order Database Diagram

### ISSUE THREAD

**Issue by ghost** [Seb1903/bovelo_manager#8]
Database Diagram

**Comment by smarbal** [comment]
@katseyres Document isn't available for everyone, make sure you clicked "Share -> Publish" (might be in advanced options)

**Comment by ghost** [comment]
@Seb1903 I changed the link.

**Comment by smarbal** [comment]
@katseyres  It's visible but it's not it. You have to go in the "**Publish**" section when you share. Here you were in "Collaborate". It lets us have a preview directly on GitHub + it won't be changeable by everyone publicly.

**Comment by ghost** [comment]
<img width="960" alt="2021-02-10_09h39_56" src="https://user-images.githubusercontent.com/46762460/107485357-f62d8c00-6b83-11eb-8a2f-6d1d7dc6413f.png">
@Seb1903 , Idk. You should have access, I put the link above from there.

**Comment by ghost** [comment]
Ok, sry I didn't change it on README.md

**Comment by smarbal** [comment]
@katseyres I know, please read my last comment. You are in the collaborate part. You should be in the **"Publier"** part .  
<img width="960" alt="107485357-f62d8c00-6b83-11eb-8a2f-6d1d7dc6413f" src="https://user-images.githubusercontent.com/35641452/107485874-a7342680-6b84-11eb-9cff-41b42cceb72b.png">

**Comment by ghost** [comment]
https://lucid.app/documents/view/a85c1e3f-c0a3-42cb-80f3-677829ead223

**Comment by Tateuf** [comment]
[Diagramme Relation DB.pdf](https://github.com/Seb1903/bovelo_manager/files/6037353/Diagramme.Relation.DB.pdf)

**Comment by Tateuf** [comment]
![Diagramme Relation DB-1](https://user-images.githubusercontent.com/75576766/109031543-1ea9a000-76c5-11eb-927e-e4f394e8fbf1.png)

**Comment by Tateuf** [comment]
[
![Database diagram](https://user-images.githubusercontent.com/75576766/114265651-60cb3e80-99f2-11eb-97b4-5db092e45305.png)
](url)
